services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r sarai/backend/requirements.txt"
    startCommand: "python sarai/backend/main.py"