// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGntH3L9gfg2eR6EyabRA4BE80Q3WEJY',
    appId: '1:176010446110:web:438f3eb1caa4ab7b97350f',
    messagingSenderId: '176010446110',
    projectId: 'sarai-4f66a',
    authDomain: 'sarai-4f66a.firebaseapp.com',
    storageBucket: 'sarai-4f66a.appspot.com',
    measurementId: 'G-E770VGJL97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARRHa0C1Fb1tUrwNek97oIl8UzWQflRlM',
    appId: '1:176010446110:android:b0433ba39adc19c897350f',
    messagingSenderId: '176010446110',
    projectId: 'sarai-4f66a',
    storageBucket: 'sarai-4f66a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEJlqSSdlV-qQmBbEOfJBPjtgmQqiokM',
    appId: '1:176010446110:ios:864ff65428ec975c97350f',
    messagingSenderId: '176010446110',
    projectId: 'sarai-4f66a',
    storageBucket: 'sarai-4f66a.appspot.com',
    iosBundleId: 'com.example.sarai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEJlqSSdlV-qQmBbEOfJBPjtgmQqiokM',
    appId: '1:176010446110:ios:864ff65428ec975c97350f',
    messagingSenderId: '176010446110',
    projectId: 'sarai-4f66a',
    storageBucket: 'sarai-4f66a.appspot.com',
    iosBundleId: 'com.example.sarai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrGntH3L9gfg2eR6EyabRA4BE80Q3WEJY',
    appId: '1:176010446110:web:26231f7237b2417697350f',
    messagingSenderId: '176010446110',
    projectId: 'sarai-4f66a',
    authDomain: 'sarai-4f66a.firebaseapp.com',
    storageBucket: 'sarai-4f66a.appspot.com',
    measurementId: 'G-1D3E9SE9S8',
  );
}
